{
    "name": "AGI - Surat Penawaran & Form PO Customer",
    "version": "16.0.1.1.0",
    "category": "Sales",
    "summary": "Generator Surat Penawaran dan Form Purchase Order (PO) Customer",
    "author": "AGI",
    "license": "LGPL-3",
    "depends": ["base", "sale", "product", "contacts", "account", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "data/surat_penawaran_data.xml",
        "data/customer_po_data.xml",
        "views/surat_penawaran_views.xml",
        "views/surat_penawaran_line_views.xml",
        "views/customer_po_views.xml",
        "report/ir_actions_report.xml",
        "report/report_surat_penawaran.xml",
        "report/report_customer_po.xml",
    ],
    "installable": True,
    "application": True,
}
